// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6a5e6a0d-2eb7-4597-ba96-9d0c9eadc9fc";

const char SSID[] = "SSID";    // Network SSID (name)
const char PASS[] = "password";    // Network password
const char DEVICE_KEY[]  = "DEVICE_KEY";    // Secret device password

void onDisplayTextChange();

String displayText;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(displayText, READWRITE, ON_CHANGE, onDisplayTextChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
